<?php
session_start();
if(empty($_SESSION["uname"]))
{
    header("refresh:0.01;url=http://localhost/AIRUP/check/homepage.php");
}
session_destroy();
header("refresh:0.01;url=http://localhost/AIRUP/check/homepage.php");
?>